---
image: ubuntu:artful

cache:
    key: apt-cache
    paths:
        - apt-cache/

before_script:
    - export APT_CACHE_DIR=`pwd`/apt-cache && mkdir -pv $APT_CACHE_DIR
    - apt-get update -yq && apt-get -o dir::cache::archives="$APT_CACHE_DIR"
     install -y meson pkg-config libdbus-1-dev gtk-doc-tools gobject-introspection
     libsqlite3-dev libglib2.0-dev libgirepository1.0-dev check valac locales lcov
    - echo "en_US UTF-8" > /etc/locale.gen
    - locale-gen en_US.UTF-8
    - export LANG=en_US.UTF-8
    - export LANGUAGE=en_US:en
    - export LC_ALL=en_US.UTF-8


build_amd64:
    stage: build
    script:
        - meson build -Denable_debug=true -Denable_doc=true -Db_coverage=true
        - cd build
        - ninja
    artifacts:
        paths:
            - ./

test_amd64:
    stage: test
    script:
        - cd build
        - ninja test
        - ninja coverage-html
    dependencies:
        - build_amd64
    artifacts:
        paths:
            - ./

pages:
    stage: deploy
    script:
        - mkdir public
        - cp -a build/docs/reference/html/* public
    only:
        - tags
        - master@accounts-sso/gsignond
    dependencies:
        - test_amd64
    artifacts:
        paths:
            - public
